name: pdf_merger
description: A new Flutter plugin for merging lists of PDF files. It supports both Android and iOS. Before using this package, make sure you have the necessary permissions and file picker setup. See the example for more details.
version: 0.0.6
homepage: https://github.com/abhay0648/pdf_merger

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.0.0"


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  external_path: ^1.0.3
  file_picker: ^8.0.6
  open_file: ^3.3.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.ril.pdf_merger
        pluginClass: PdfMergerPlugin
      ios:
        pluginClass: PdfMergerPlugin
